version: "3"

services:

  nginx:
    image: "${PROJECT_NAME}/nginx:dev"
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}_nginx"
    ports:
      - '80:80' #thamelmart
      - '443:443' #thamelmar
    volumes:
      - ./api:/var/www/api
      - ./nginx/log:/var/log/nginx
    networks:
      backend:
        aliases:
          - api.techbizz.test
      frontend:
        aliases:
          - consumer.techbizz.test
          - service.techbizz.test
    depends_on:
      - api
      - consumer
      - service

  consumer:
    container_name: "${PROJECT_NAME}_consumer"
    image: "${PROJECT_NAME}/consumer:dev"
    build:
      context: ./consumer
      dockerfile: Dockerfile
    restart: unless-stopped
    user: "1000:1000"
    environment:
      REACT_API_HOST: ''
      REACT_PUSHER_APP_ID: #####
      REACT_PUSHER_APP_KEY: #####
      REACT_APP_API_BASE_URL: http://api.techbizz.test/api
      REACT_PUSHER_HOST:
      REACT_PUSHER_APP_CLUSTER: ###
      REACT_PUSHER_PORT: 80
      REACT_PUSHER_SCHEME: http
    volumes:
      - ./consumer:/consumer
    ports:
      - '3000:3000'
    command: sh -c "yarn && yarn dev"
    networks:
      backend:
        aliases:
          - api.techbizz.test
      frontend:
        aliases:
          - consumer.techbizz.test
          - service.techbizz.test

  service:
    container_name: "${PROJECT_NAME}_service"
    image: "${PROJECT_NAME}/service:dev"
    build:
      context: ./service
      dockerfile: Dockerfile
    restart: unless-stopped
    user: "1000:1000"
    environment:
      REACT_API_HOST: ''
      REACT_PUSHER_APP_ID: #####
      REACT_PUSHER_APP_KEY: #####
      REACT_APP_API_BASE_URL: http://api.techbizz.test/api
      REACT_PUSHER_HOST:
      REACT_PUSHER_APP_CLUSTER: ###
      REACT_PUSHER_PORT: 80
      REACT_PUSHER_SCHEME: http
    volumes:
      - ./service:/service
    ports:
      - '3001:3001'
    command: sh -c "yarn && yarn dev"
    networks:
      backend:
        aliases:
          - api.techbizz.test
      frontend:
        aliases:
          - consumer.techbizz.test
          - service.techbizz.test

  api:
    container_name: "${PROJECT_NAME}_php"
    image: "${PROJECT_NAME}/api:dev"
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    user: "apache:apache"
    working_dir: /var/www/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./api/conf.d/php.ini:/usr/local/etc/php/php.ini
      - ./api/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./api/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./api:/var/www/api
    # command: "composer install"
    environment:
      PHP_IDE_CONFIG: serverName=gravity
    ports:
      - '9000:9000'
    networks:
      backend:
        aliases:
          - api.techbizz.test
      frontend:
        aliases:
          - consumer.techbizz.test
          - service.techbizz.test
    depends_on:
      - mysql
      - pma
      - redis

  mysql:
    container_name: "${PROJECT_NAME}_mysql"
    image: "${PROJECT_NAME}/mysql:dev"
    build: ./mysql
    volumes:
      - "persisted_volume:/var/lib/mysql"
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: ${TIMEZONE}
    networks:
      - backend

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8090:80"
    networks:
      - backend

  redis:
    build: ./redis
    container_name: "${PROJECT_NAME}_redis"
    image: "${PROJECT_NAME}/redis:dev"
    volumes:
      - "persisted_volume:/data"
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  persisted_volume:
