name: Consumer

on:
  push:
    branches: [ main ]

jobs:
  consumer-tests:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      working-directory: ./consumer
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build