# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

##########################################
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
###########################################
    - name: Install Service dependencies
      working-directory: ./service
      run: yarn
      env:
        PUSHER_APP_ID=#####
        PUSHER_APP_KEY=#####
        API_BASE_URL=https://api.techbizz.test/api
        API_AUTH_URL=https://api.techbizz.test/api/auth
        PUSHER_HOST=
        PUSHER_APP_CLUSTER=###
        PUSHER_PORT=80
        PUSHER_SCHEME=http

    - name: Install Consumer dependencies
      working-directory: ./consumer
      run: yarn
      env:
        PUSHER_APP_ID=#####
        PUSHER_APP_KEY=#####
        API_BASE_URL=https://api.techbizz.test/api
        API_AUTH_URL=https://api.techbizz.test/api/auth
        PUSHER_HOST=
        PUSHER_APP_CLUSTER=###
        PUSHER_PORT=80
        PUSHER_SCHEME=http
##########################################
    - name: Run the Service tests
      working-directory: ./service
      run: yarn lint    
    
    - name: Run the Consumer tests
      working-directory: ./consumer
      run: yarn lint
##########################################
    - name: Service Build
      working-directory: ./service
      run: yarn build
      env:
        PUSHER_APP_ID=#####
        PUSHER_APP_KEY=#####
        API_BASE_URL=https://api.techbizz.test/api
        API_AUTH_URL=https://api.techbizz.test/api/auth
        PUSHER_HOST=
        PUSHER_APP_CLUSTER=###
        PUSHER_PORT=80
        PUSHER_SCHEME=http    

    - name: Consumer Build
      working-directory: ./consumer
      run: yarn build
      env:
        PUSHER_APP_ID=#####
        PUSHER_APP_KEY=#####
        API_BASE_URL=https://api.techbizz.test/api
        API_AUTH_URL=https://api.techbizz.test/api/auth
        PUSHER_HOST=
        PUSHER_APP_CLUSTER=###
        PUSHER_PORT=80
        PUSHER_SCHEME=http
##########################################